apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-grafana-client
  namespace: grafana
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-grafana-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        client-id: grafana
        client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-grafana-client
        version: CURRENT
        decodingStrategy: None
