---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-github-connector
  namespace: dex
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-github-connector
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: GITHUB_DEX_CLIENT_ID
    remoteRef:
      key: GITHUB_DEX_CLIENT_ID
      version: CURRENT
      decodingStrategy: None
  - secretKey: GITHUB_DEX_CLIENT_SECRET
    remoteRef:
      key: GITHUB_DEX_CLIENT_SECRET
      version: CURRENT
      decodingStrategy: None
