---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-github-connector
  namespace: dex
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-github-connector-test
    creationPolicy: Owner
  data:
  - secretKey: GITHUB_DEX_CLIENT_ID
    remoteRef:
      key: ITHUB_DEX_CLIENT_ID
      version: v1
      decodingStrategy: None
