apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  path: ./gitops/core/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
