apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/prometheus
  prune: true
  dependsOn:
    - name: external-secrets
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
